### PR TITLE
Disable date guessing. Contribute to energy-data/energydata.info#1

### PR DESCRIPTION
**Pull request by olafveerman**

### CODE REVIEW

**Comment by kamicut** [comment]
@olafveerman do we need to include Date in the TYPES array? In the hotfix we changed TYPES to `[messytables.StringType, messytables.DecimalType, messytables.IntegerType]`

**Comment by olafveerman** [comment]
Yup, thanks for catching that. Removed in commit above @kamicut

**Comment by kamicut** [comment]
LGTM

**Comment by olafveerman** [comment]
Contributed to: energy-data/energydata.info#1

**Pull request merged**
